name: peminjam_perpustakaan_kelasc
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  get: 4.6.6
  google_sign_in: ^6.1.6
  flutter_native_splash: ^2.0.0
  date_time_picker: ^2.0.0
  hexcolor: ^3.0.1
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.4
  iconsax: ^0.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#272727"
  image: assets/images/logodp.png
  image_dark: assets/images/logodp.png

  android_12:
    image: assets/images/logodp.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logodp.png
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
